/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto1;

import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author sergi
 */
public class Ventana extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ventana.class.getName());

    private double firstNumber = 0.0;
    private String operator = "";
    private boolean isOperatorClicked = false;
    private StringBuilder expression = new StringBuilder();

    public Ventana() {
        initComponents();
        caja.setText(""); // Initialize empty
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        mensajentrante1 = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        caja = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();

        mensajentrante1.setText("-");

        jButton17.setText("Sen x");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 0));
        setForeground(java.awt.Color.pink);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setBackground(java.awt.Color.cyan);
        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setForeground(java.awt.Color.black);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CALCULADORA");
        jLabel1.setToolTipText("");
        jLabel1.setMaximumSize(new java.awt.Dimension(60, 21));
        jLabel1.setPreferredSize(new java.awt.Dimension(60, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_LEADING;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        getContentPane().add(jLabel1, gridBagConstraints);

        caja.setBackground(java.awt.Color.cyan);
        caja.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        caja.setForeground(java.awt.Color.black);
        caja.setToolTipText("");
        caja.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        caja.setMaximumSize(new java.awt.Dimension(162, 30));
        caja.setPreferredSize(new java.awt.Dimension(162, 30));
        caja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_LEADING;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        getContentPane().add(caja, gridBagConstraints);

        jButton1.setBackground(java.awt.Color.cyan);
        jButton1.setForeground(java.awt.Color.black);
        jButton1.setText("1");
        jButton1.setAlignmentX(0.5F);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_LEADING;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        getContentPane().add(jButton1, gridBagConstraints);

        jButton2.setBackground(java.awt.Color.cyan);
        jButton2.setForeground(java.awt.Color.black);
        jButton2.setText("2");
        jButton2.setAlignmentX(0.5F);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_LEADING;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        getContentPane().add(jButton2, gridBagConstraints);

        jButton3.setBackground(java.awt.Color.cyan);
        jButton3.setForeground(java.awt.Color.black);
        jButton3.setText("3");
        jButton3.setAlignmentX(0.5F);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_LEADING;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        getContentPane().add(jButton3, gridBagConstraints);

        jButton4.setBackground(java.awt.Color.cyan);
        jButton4.setForeground(java.awt.Color.black);
        jButton4.setText("4");
        jButton4.setAlignmentX(0.5F);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_LEADING;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        getContentPane().add(jButton4, gridBagConstraints);

        jButton5.setBackground(java.awt.Color.cyan);
        jButton5.setForeground(java.awt.Color.black);
        jButton5.setText("5");
        jButton5.setAlignmentX(0.5F);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_LEADING;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        getContentPane().add(jButton5, gridBagConstraints);

        jButton6.setBackground(java.awt.Color.cyan);
        jButton6.setForeground(java.awt.Color.black);
        jButton6.setText("6");
        jButton6.setAlignmentX(0.5F);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_LEADING;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        getContentPane().add(jButton6, gridBagConstraints);

        jButton7.setBackground(java.awt.Color.cyan);
        jButton7.setForeground(java.awt.Color.black);
        jButton7.setText("7");
        jButton7.setAlignmentX(0.5F);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_LEADING;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        getContentPane().add(jButton7, gridBagConstraints);

        jButton8.setBackground(java.awt.Color.cyan);
        jButton8.setForeground(java.awt.Color.black);
        jButton8.setText("8");
        jButton8.setAlignmentX(0.5F);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_LEADING;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        getContentPane().add(jButton8, gridBagConstraints);

        jButton9.setBackground(java.awt.Color.cyan);
        jButton9.setForeground(java.awt.Color.black);
        jButton9.setText("9");
        jButton9.setAlignmentX(0.5F);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_LEADING;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        getContentPane().add(jButton9, gridBagConstraints);

        jButton10.setBackground(java.awt.Color.cyan);
        jButton10.setForeground(java.awt.Color.black);
        jButton10.setText("+");
        jButton10.setAlignmentX(0.5F);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_LEADING;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        getContentPane().add(jButton10, gridBagConstraints);

        jButton11.setBackground(java.awt.Color.cyan);
        jButton11.setForeground(java.awt.Color.black);
        jButton11.setText("=");
        jButton11.setAlignmentX(0.5F);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_LEADING;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        getContentPane().add(jButton11, gridBagConstraints);

        jButton12.setBackground(java.awt.Color.cyan);
        jButton12.setForeground(java.awt.Color.black);
        jButton12.setText("x");
        jButton12.setAlignmentX(0.5F);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_LEADING;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        getContentPane().add(jButton12, gridBagConstraints);

        jButton13.setBackground(java.awt.Color.cyan);
        jButton13.setForeground(java.awt.Color.black);
        jButton13.setText("-");
        jButton13.setAlignmentX(0.5F);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_LEADING;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        getContentPane().add(jButton13, gridBagConstraints);

        jButton14.setBackground(java.awt.Color.cyan);
        jButton14.setForeground(java.awt.Color.black);
        jButton14.setText("/");
        jButton14.setAlignmentX(0.5F);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_LEADING;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        getContentPane().add(jButton14, gridBagConstraints);

        jButton15.setBackground(java.awt.Color.cyan);
        jButton15.setForeground(java.awt.Color.black);
        jButton15.setText("CE");
        jButton15.setAlignmentX(0.5F);
        jButton15.setMaximumSize(new java.awt.Dimension(54, 27));
        jButton15.setMinimumSize(new java.awt.Dimension(27, 27));
        jButton15.setPreferredSize(new java.awt.Dimension(54, 27));
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_LEADING;
        gridBagConstraints.insets = new java.awt.Insets(1, 0, 1, 0);
        getContentPane().add(jButton15, gridBagConstraints);

        jButton16.setBackground(java.awt.Color.cyan);
        jButton16.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jButton16.setForeground(java.awt.Color.black);
        jButton16.setText("Sen x");
        jButton16.setMaximumSize(new java.awt.Dimension(54, 27));
        jButton16.setMinimumSize(new java.awt.Dimension(27, 27));
        jButton16.setPreferredSize(new java.awt.Dimension(54, 27));
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        getContentPane().add(jButton16, gridBagConstraints);

        jButton18.setBackground(java.awt.Color.cyan);
        jButton18.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jButton18.setForeground(java.awt.Color.black);
        jButton18.setText("Cos x");
        jButton18.setMaximumSize(new java.awt.Dimension(54, 27));
        jButton18.setMinimumSize(new java.awt.Dimension(27, 27));
        jButton18.setPreferredSize(new java.awt.Dimension(54, 27));
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 3;
        getContentPane().add(jButton18, gridBagConstraints);

        jButton19.setBackground(java.awt.Color.cyan);
        jButton19.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jButton19.setForeground(java.awt.Color.black);
        jButton19.setText("Tan x");
        jButton19.setMaximumSize(new java.awt.Dimension(54, 27));
        jButton19.setMinimumSize(new java.awt.Dimension(27, 27));
        jButton19.setPreferredSize(new java.awt.Dimension(54, 27));
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 4;
        getContentPane().add(jButton19, gridBagConstraints);

        jButton20.setBackground(java.awt.Color.cyan);
        jButton20.setForeground(java.awt.Color.black);
        jButton20.setText("π");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        getContentPane().add(jButton20, gridBagConstraints);

        jButton21.setBackground(java.awt.Color.cyan);
        jButton21.setForeground(new java.awt.Color(0, 0, 0));
        jButton21.setText(")");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        getContentPane().add(jButton21, gridBagConstraints);

        jButton22.setBackground(java.awt.Color.cyan);
        jButton22.setForeground(java.awt.Color.black);
        jButton22.setText("0");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        getContentPane().add(jButton22, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String textoActual = caja.getText();
        String numero1 = "1";
        expression.append(numero1);
        caja.setText(expression.toString());
        isOperatorClicked = false;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String textoActual = caja.getText();
        String numero5 = "5";
        expression.append(numero5);
        caja.setText(expression.toString());
        isOperatorClicked = false;
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String textoActual = caja.getText();
        String numero6 = "6";
        expression.append(numero6);
        caja.setText(expression.toString());
        isOperatorClicked = false;
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String textoActual = caja.getText();
        String numero2 = "2";
        expression.append(numero2);
        caja.setText(expression.toString());
        isOperatorClicked = false;      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String textoActual = caja.getText();
        String numero3 = "3";
        expression.append(numero3);
        caja.setText(expression.toString());
        isOperatorClicked = false;
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String textoActual = caja.getText();
        String numero4 = "4";
        expression.append(numero4);
        caja.setText(expression.toString());
        isOperatorClicked = false;
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String textoActual = caja.getText();
        String numero7 = "7";
        expression.append(numero7);
        caja.setText(expression.toString());
        isOperatorClicked = false;
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        String textoActual = caja.getText();
        String numero8 = "8";
        expression.append(numero8);
        caja.setText(expression.toString());
        isOperatorClicked = false;
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        String textoActual = caja.getText();
        String numero9 = "9";
        expression.append(numero9);
        caja.setText(expression.toString());
        isOperatorClicked = false;
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
if (!isOperatorClicked && expression.length() > 0) {
        expression.append(" + ");
        caja.setText(expression.toString());
        isOperatorClicked = true;
    }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
try {
        String[] tokens = expression.toString().trim().split("\\s+");
        List<Double> numbers = new ArrayList<>();
        List<String> operators = new ArrayList<>();

        // Parse tokens
        for (int i = 0; i < tokens.length; i++) {
            String token = tokens[i];
            if (token.matches("-?\\d+(\\.\\d*)?")) { // Updated regex to match integers and decimals
                numbers.add(Double.parseDouble(token));
            } else if (token.matches("sin\\(|cos\\(|tan\\(")) { // Trigonometric functions
                if (i + 2 < tokens.length && tokens[i + 1].matches("-?\\d+(\\.\\d*)?") && tokens[i + 2].equals(")")) {
                    double angle = Double.parseDouble(tokens[i + 1]);
                    double result;
                    switch (token) {
                        case "sin(":
                            result = Math.sin(Math.toRadians(angle));
                            break;
                        case "cos(":
                            result = Math.cos(Math.toRadians(angle));
                            break;
                        case "tan(":
                            if (Math.abs(angle % 180) == 90) { // Handle undefined tan (90°, 270°, etc.)
                                caja.setText("Error");
                                expression = new StringBuilder();
                                isOperatorClicked = false;
                                return;
                            }
                            result = Math.tan(Math.toRadians(angle));
                            break;
                        default:
                            throw new NumberFormatException("Invalid function");
                    }
                    numbers.add(result);
                    i += 2; // Skip angle and closing parenthesis
                } else {
                    throw new NumberFormatException("Invalid trig expression");
                }
            } else if (token.matches("[+\\-*/]")) { // Operators
                operators.add(token);
            }
        }

        // Evaluate * and /
        for (int i = 0; i < operators.size(); ) {
            if (operators.get(i).equals("*") || operators.get(i).equals("/")) {
                double left = numbers.get(i);
                double right = numbers.get(i + 1);
                double result = operators.get(i).equals("*") ? left * right : left / right;
                if (operators.get(i).equals("/") && right == 0) {
                    caja.setText("Error");
                    expression = new StringBuilder();
                    isOperatorClicked = false;
                    return;
                }
                numbers.set(i, result);
                numbers.remove(i + 1);
                operators.remove(i);
            } else {
                i++;
            }
        }

        // Evaluate + and -
        double result = numbers.get(0);
        for (int i = 0; i < operators.size(); i++) {
            result = operators.get(i).equals("+") ? result + numbers.get(i + 1) : result - numbers.get(i + 1);
        }

        if (Double.isNaN(result) || Double.isInfinite(result)) {
            caja.setText("Error");
        } else {
            caja.setText(result == (int) result ? String.valueOf((int) result)
                    : String.format("%.6f", result).replaceAll("0*$", "").replaceAll("\\.$", ""));
        }
        expression = new StringBuilder(String.valueOf(result));
        operator = "";
        isOperatorClicked = false;
    } catch (NumberFormatException | IndexOutOfBoundsException e) {
        caja.setText("Error");
        expression = new StringBuilder();
        operator = "";
        isOperatorClicked = false;
    }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
if (!isOperatorClicked && expression.length() > 0) {
        expression.append(" * ");
        caja.setText(expression.toString());
        isOperatorClicked = true;
    }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
if (!isOperatorClicked && expression.length() > 0) {
        expression.append(" - ");
        caja.setText(expression.toString());
        isOperatorClicked = true;
    }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
if (!isOperatorClicked && expression.length() > 0) {
        expression.append(" / ");
        caja.setText(expression.toString());
        isOperatorClicked = true;
    }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        caja.setText("");
        expression = new StringBuilder();
        firstNumber = 0.0;
        operator = "";
        isOperatorClicked = false;
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
    expression.append("sin(");
    caja.setText(expression.toString());
    isOperatorClicked = false;
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
    expression.append("cos(");
    caja.setText(expression.toString());
    isOperatorClicked = false;
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
    expression.append("tan(");
    caja.setText(expression.toString());
    isOperatorClicked = false;
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
    String textoActual = caja.getText(); // Optional, for consistency with number buttons
    String numeropi = "3.14";
    expression.append(numeropi);
    caja.setText(expression.toString());
    isOperatorClicked = false;
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
    expression.append(")");
    caja.setText(expression.toString());
    isOperatorClicked = false;
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        String textoActual = caja.getText();
        String numero0 = "0";
        expression.append(numero0);
        caja.setText(expression.toString());
        isOperatorClicked = false;   
    }//GEN-LAST:event_jButton22ActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new Ventana().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField caja;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel mensajentrante1;
    // End of variables declaration//GEN-END:variables
}
